name: connecthub
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.1
  firebase_database: ^10.5.5
  cupertino_icons: ^1.0.5
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  firebase_storage: ^11.7.4 
  image_picker: ^1.1.1 
  file_picker: ^8.0.3
  msix: ^3.16.7
  persistent_bottom_nav_bar: ^5.0.2
  flutter_rating_bar: ^4.0.1
  #flutter_image_compress: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/login&registration/
